services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=2QNP5kGEJyzxcWCV98IOCAQq80m_3Xk1z47dxX1DPRhn4naC4
    command:
      - "http"
      - "bot:8000"
    ports:
      - "4040:4040"